# Generated by Django 5.2.10 on 2026-01-20 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcoupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='serial_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
