# Generated by Django 5.2.10 on 2026-01-20 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcoupon', '0002_alter_card_serial_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-created_at'], 'verbose_name': 'カード', 'verbose_name_plural': 'カード'},
        ),
        migrations.AddField(
            model_name='card',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='有効化日時'),
        ),
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.PositiveIntegerField(default=1000, verbose_name='残高(pt)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='ロック中（2重決済防止）'),
        ),
        migrations.AlterField(
            model_name='card',
            name='serial_number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='シリアル番号'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('unused', '未使用'), ('active', '有効'), ('used', '使用済み')], default='unused', max_length=10, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='card',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='使用済み日時'),
        ),
    ]
