# Generated by Django 5.2.10 on 2026-01-29 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcoupon', '0003_alter_card_options_card_activated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('unused', '未使用'), ('active', '有効'), ('used', '使用済み'), ('deleted', '削除済み')], default='unused', max_length=10, verbose_name='ステータス'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('card_create', 'カード作成'), ('card_activate', 'カード有効化'), ('card_edit', 'カード編集'), ('card_delete', 'カード削除'), ('product_create', '商品作成'), ('product_edit', '商品編集'), ('product_delete', '商品削除'), ('transaction_create', '取引作成'), ('transaction_cancel', '取引キャンセル'), ('user_create', 'ユーザー作成'), ('user_edit', 'ユーザー編集'), ('user_delete', 'ユーザー削除'), ('user_login', 'ログイン'), ('user_logout', 'ログアウト')], max_length=50, verbose_name='アクション')),
                ('description', models.TextField(verbose_name='説明')),
                ('target_model', models.CharField(blank=True, max_length=50, verbose_name='対象モデル')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='対象ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='追加データ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='実行日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='実行ユーザー')),
            ],
            options={
                'verbose_name': 'アクティビティログ',
                'verbose_name_plural': 'アクティビティログ',
                'ordering': ['-created_at'],
                'permissions': [('view_activity_log', 'アクティビティログを閲覧可能')],
            },
        ),
    ]
