# Generated by Django 6.0.1 on 2026-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcoupon', '0005_temporarycardcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('card_create', 'カード作成'), ('card_activate', 'カード有効化'), ('card_edit', 'カード編集'), ('card_delete', 'カード削除'), ('product_create', '商品作成'), ('product_edit', '商品編集'), ('product_delete', '商品削除'), ('transaction_create', '取引作成'), ('transaction_complete', '取引完了'), ('transaction_cancel', '取引キャンセル'), ('user_create', 'ユーザー作成'), ('user_edit', 'ユーザー編集'), ('user_delete', 'ユーザー削除'), ('user_login', 'ログイン'), ('user_logout', 'ログアウト')], max_length=50, verbose_name='アクション'),
        ),
    ]
