
services:
  django:
    image: ghcr.io/mikannohako/microcoupon:latest
    build: 
      context: ./django
      dockerfile: Dockerfile
    container_name: microcoupon-django
    command:  >
      sh -c "
      python manage.py runserver 0.0.0.0:8000
      "
    volumes: 
      - ./django:/app
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    expose:
      - "8000"

  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: microcoupon-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: microcoupon-nginx
    ports:
      - "0.0.0.0:8080:80"
    env_file:
      - .env
    environment:
      - ADMIN_PATH=${ADMIN_PATH}
      - NGINX_ADMIN_PATH=/${ADMIN_PATH}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./django/staticfiles:/app/staticfiles
      - ${BASIC_AUTH_FILE_HOST:-./nginx/.htpasswd.dummy}:/etc/nginx/.htpasswd:ro
    depends_on:
      - django
      - db

volumes:
  static_volume:
  pgdata: 
