# Generated by Django 5.2.10 on 2026-01-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='account.room', verbose_name='教室'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['room', 'display_order', 'name'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('room', 'name')},
        ),
    ]
