# Generated by Django 5.2.10 on 2026-01-20 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('microcoupon', '0003_alter_card_options_card_activated_at_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.PositiveIntegerField(verbose_name='合計金額(pt)')),
                ('status', models.CharField(choices=[('completed', '完了'), ('failed', '失敗'), ('cancelled', 'キャンセル')], default='completed', max_length=20, verbose_name='ステータス')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='決済日時')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='操作者')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='microcoupon.card', verbose_name='カード')),
            ],
            options={
                'verbose_name': '決済ログ',
                'verbose_name_plural': '決済ログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='品名')),
                ('product_price', models.PositiveIntegerField(verbose_name='単価(pt)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='商品')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.transaction', verbose_name='決済')),
            ],
            options={
                'verbose_name': '決済明細',
                'verbose_name_plural': '決済明細',
            },
        ),
    ]
