# Generated by Django 5.2.10 on 2026-01-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcoupon', '0003_alter_card_options_card_activated_at_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='microcoupon.card', verbose_name='カード'),
        ),
    ]
